const os = require('os')

console.log(os.platform())
console.log(os.arch())
console.log(os.cpus()[0])
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.homedir())
console.log(os.uptime())
console.log(os.release())
